### ISSUE TITLE
standard_sqi.msq_sqi missing import line

### ISSUE THREAD

**Issue by bahp** [meta00/vital_sqi#54]
from vital_sqi.common import PeakDectector.

Note that function raises some warning when used "name 'iscalar' is not defined.

https://github.com/meta00/vital_sqi/blob/6d332b705003c5d70b4ea0eb1e0aa768266c3e7a/vital_sqi/sqi/standard_sqi.py#L276

**Comment by Koaha** [comment]
Thanks for addressing the issue. PeakDetector has been imported in standard_sqi. Regarding the 'isscalar' function, it is rewritten to be imported from numpy package and seems to run ok from my side. Please let me know if the problem still occurs
