### ISSUE TITLE
pip install vital_sqi

### ISSUE THREAD

**Issue by KooroshMotaman** [meta00/vital_sqi#92]
Hello
I want to use the vital_sqi package but I couldn't install it. would you please help me?

**Comment by Koaha** [comment]
Hi,
We are going to upload this into PyPi soon. At the moment, you can install the package by cloning the src code and install it locally

```
git clone https://github.com/meta00/vital_sqi
cd vital_sqi
pip install -e .
```

the package docs can be found at https://vitalsqi.readthedocs.io/en/latest/

**Comment by Koaha** [comment]
The package is available now at [PyPI](https://pypi.org/project/vital-sqi/)
